import 'dart:async';
import 'dart:developer';

import 'package:collection/collection.dart';
import 'package:flame/components.dart';
import 'package:flame/extensions.dart';
import 'package:flame/input.dart';
import 'package:flutter/material.dart' hide Image;
import 'package:states_rebuilder/states_rebuilder.dart';
import 'package:transoxiana/components/battle/battle.dart';
import 'package:transoxiana/components/campaign/province.dart';
import 'package:transoxiana/components/campaign/weather.dart';
import 'package:transoxiana/components/game/game.dart';
import 'package:transoxiana/components/game_stream/game_stream.dart';
import 'package:transoxiana/components/shared/army.dart';
import 'package:transoxiana/components/shared/components_render_priority.dart';
import 'package:transoxiana/components/shared/events/events.dart';
import 'package:transoxiana/components/shared/nation.dart';
import 'package:transoxiana/components/shared/traversable_map.dart';
import 'package:transoxiana/data/army_modes.dart';
import 'package:transoxiana/data/campaign_data_source.dart';
import 'package:transoxiana/data/constants.dart';
import 'package:transoxiana/data/game_dates.dart';
import 'package:transoxiana/data/render_callback.dart';
import 'package:transoxiana/data/season.dart';
import 'package:transoxiana/data/temporary_game_data.dart';
import 'package:transoxiana/generated/l10n.dart';
import 'package:transoxiana/services/ai.dart';
import 'package:transoxiana/services/python_interface.dart';
import 'package:transoxiana/services/save_service.dart';
import 'package:transoxiana/services/shared_preferences_keys.dart';
import 'package:transoxiana/services/tutorial/tutorial_states.dart';
import 'package:transoxiana/widgets/base/dialogues.dart';
import 'package:utils/utils.dart';

part 'campaign_events.dart';
part 'campaign_loader.dart';
part 'campaign_loader_runner.dart';
part 'campaign_loading.dart';
part 'campaign_methods.dart';
part 'campaign_ref.dart';
part 'campaign_render.dart';
part 'campaign_state.dart';

typedef CampaignId = String;
